#!/bin/sh -e

# sea, the POSIX shell-script package manager

log () {
    # print fancy outputs
    printf "%b\n" "\u001b[36m[#] \u001b[0m$1"
}

warning () {
    # print fancy warnings
    printf "%b\n" "\u001b[35m[!] \u001b[33m\u001b[1m$1"
}
