#!/bin/sh -e

# sea, the POSIX shell-script package manager

log () {
    # print fancy outputs
    printf "%b\n" "\u001b[36m[#] \u001b[0m$1"
}

warning () {
    # print fancy warnings
    printf "%b\n" "\u001b[35m[!] \u001b[33m\u001b[1m$1"
}

usage () {
    # prints the usage of a command depending on the arguments
    printf "\n"
    printf "Usage: sea [OPTION] [ACTION] <ARGS>\n\n"
    printf "Options: TBA\n\n"
    printf "Actions:\n"
    printf "    i,install <pkg>       | install package(s)\n"
    printf "   	q,query <mode> <args> | search for package(s)\n"
    printf "   	r,remove <pkg>        | remove package(s)\n"
    printf "   	s,submit <file>	      | upload package for approval\n"
    printf "   	u,upgrade [pkg]	      | update package(s) to latest versions\n"
    printf "\n"
}

usage
