.TH SEA 1
.SH NAME
sea - package management tool for sea packages.

.SH SYNOPSIS
.B sea
\fIaction\fR
[\fBFLAGS\fR]
\fItargets\fR...

.SH DESCRIPTION
.B sea
is a package management utility written in POSIX shell script for Shell scripts. It has been designed to be simple as well for hosting repos than managing packages and features installation, uninstallation, query, patching and automatic upgrade of simple packages from online repositories.

.SH ACTIONS

\" TODO Actions and Options
